### PR TITLE
[1.19.2] Move recipes to using the forge conditional recipes system

### LINKED ISSUE #3: 1.20.1 release breaks Recipes
Messes with the recipes, the inscriber recipe is gone with this installed.

```
[main/ERROR] [net.minecraft.world.item.crafting.RecipeManager/]: Parsing error loading recipe ae2:inscriber/certus_quartz_dust: com.google.gson.JsonSyntaxException: Empty ingredient not allowed here
```
and similiar errors^

### PR DESCRIPTION
**Pull request by ChiefArug**
This fixes #3 on 1.19.2 as the recipe never loads instead of loading a bad json.

This also allows a config option to disable recipe overwriting, which has been added to the new common config file. It is common because server configs actually load after recipes, and the conditions are checked when recipes load. Because Forge configs support hot reloading, you can modify and save the config (not using notepad++, known bug in Forge) and then /reload to toggle this config option without needing a game restart.
This also means the new recipes keep the same recipe id, for any mods that reference recipes that way.
A config option is prefferable to the old datapack option as disabling the datapack cannot be done without first loading it, then reloading all game data with it disabled, which can be laggy in big packs or low end computers. A config option could also be added to not load the datapack (by checking the value in the pack finder), which would not have those issues, but I chose to go for the recipe condition option instead.

Finally there is some cleanup. There was a line in the mod constructor to add it to the main event bus, but no listeners, which has been removed.
All the recipes involving crystal seeds have been removed, as the seed items no longer exist (this was causing a fair amount of spam in the log too). There are new recipes involving the new crystal growing blocks, however I have not added those and have left those to the author to add.

If this PR is not accepted due to the author preffering the datapack system, at least change your disabling jsons to this: 
```json
{"conditions": [{"type": "forge:false"}]}
```
which prevents the recipe from loading or erroring and also solves #3.

### CODE REVIEW

**Comment by ChiefArug** [comment]
This should be easy to port to 1.20.1, just cherry pick and resolve the merge conflicts in the main mod class.

**Comment by furuochen-dev** [comment]
Wow this look like a lot of work, let me quickly check it out.

**Comment by MadSciSlack** [comment]
I second the Chief's suggestion here.  It solves multiple issues, and this mod could use some config options anyway.  We're tired of remaking AE2 recipes because your mod nukes them, and nobody knows to remove the bad datapack before it's too late.

**Comment by furuochen-dev** [comment]
@ChiefArug You broke everything by not making a separate datapack 😔. Sorry I should've reviewed better earlier. The reason I created a separate datapack is to make sure it loads **after** AE2's mod resource. Due to the fact that you made it into this mod's resource, and forge mod (resource) loading order is not guaranteed, every time someone creates a map, there is a chance of the this thing being completely useless.

**Comment by RuochenFu21** [comment]
Reverted.

**Comment by ChiefArug** [comment]
You can set your mod to load after AE2 in your mods.toml.

**Comment by furuochen-dev** [comment]
> You can set your mod to load after AE2 in your mods.toml.

Wait you can? What about the worlds that are already created before this update?

**Comment by ChiefArug** [comment]
I believe all the mod datapacks are lumped together into one main datapack so that shouldn't be an issue.

**Comment by furuochen-dev** [comment]
> I believe all the mod datapacks are lumped together into one main datapack so that shouldn't be an issue.

The datapack order are determined when world creation, which means the world created in older versions might have some datapack order issues. It's fine I guess. I hope it will be alterable with the datapack command.

**Pull request merged**
